#########################
## Sample Sass Lint File
#########################
options:
  merge-default-rules: true
  formatter: stylish
files:
  include: 'app/**/*.scss'
rules:
  clean-import-paths: 2
  empty-args:
    - 2
    -
      include: true
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  hex-length: 0
  hex-notation: 2
  indentation: 2
  leading-zero:
    - 2
    -
      include: true
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
  no-color-keywords: 0
  no-color-literals: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  one-declaration-per-line: 2
  property-sort-order: 2
  quotes: 2
  single-line-per-selector: 2
  space-after-colon: 2
  space-after-comma: 2
  space-before-brace:
    - 2
    -
      include: true
  space-before-colon: 2
  trailing-semicolon: 2
  variable-for-property:
    - 2
    -
      properties:
        - content
  zero-unit: 2
